using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using VDI.Demo.EntityFrameworkCore;
using VDI.Demo.PropertySystemDB.MasterPlan.Unit;

namespace VDI.Demo.Migrations.PropertySystemDb.Seed
{
    public class DetailCreator
    {
        private readonly PropertySystemDbContext _context;

        public DetailCreator(PropertySystemDbContext context)
        {
            _context = context;
        }

        public void Create()
        {
            CreateSeed();
        }

        private void CreateSeed()
        {
            List<MS_Detail> InitialDetail = new List<MS_Detail>();
            List<String> listDetail = new List<string>()
            {

                " R3Cb, R3-Cb",
                "-,-",
                "1,TIPE-1",
                "112AC,112 A/B/C",
                "112D,112 A/B/C",
                "12,Combine 12x15",
                "123AC,123 A/B/C",
                "123D,123 D/E/F",
                "123DE,123 D/E/F",
                "12CDS,12x15",
                "12HOK,12x15",
                "12IR1,12x15",
                "12IR2,12x15",
                "12IR3,12x15",
                "12IRR,12x15",
                "12REG,12x15",
                "136AB,136 A/B",
                "14,Combine 14x18",
                "14CDS,14x15",
                "14HOK,14x15",
                "14IR1,14x15",
                "14IR2,14x15",
                "14IRR,14x15",
                "14REG,14x15",
                "16,Combine 16x20",
                "16HOK,16x15",
                "16IR1,16x15",
                "16IR2,16x15",
                "16IR3,16x15",
                "16IRR,16x15",
                "16REG,16x15",
                "1A0,ALHAMBRA (PR)",
                "1AD,A (std) / D (ex1)",
                "1AT,ATHENA",
                "1BE,B (std) / E (ex1)",
                "1BR,1 Bedroom",
                "1CF,C (std) / F (ex1)",
                "1H0,HEIAN (PR)",
                "1L0,ALVILA (PR)",
                "1LU,LUCERNE (PR)",
                "1M0,MEIJI (PR)",
                "1MB,MONT BLANC (PR)",
                "1MR,ST. MORITZ (PR)",
                "1MX,MONTREUX (PR)",
                "2,TIPE-2",
                "218AB,218 A/B",
                "2BR,2BR",
                "2BR',2BR'",
                "2BR0,2BR",
                "2BR1,2BR'",
                "2BRD,2BR DELUXE",
                "2BRP,2BR PREMIUM",
                "2BRS,2BR SUITES",
                "2DU,DUPLEX (CR)",
                "2GU,SEAGULL (CR)",
                "2VE,SEAVIEW (CR)",
                "2VS,SEAVISTA (CR)",
                "3,TIPE-3",
                "3.5LT,3.5 LANTAI",
                "375,TYPE-375",
                "399,TYPE-399",
                "3BR,3BR",
                "3BR\"',3BR\"'",
                "3BR',3BR'",
                "3BR0,3BR",
                "3BR1,3BR'",
                "3BR2,3BR\"",
                "3BR3,3BR\"'",
                "3TAB,Blok TA-11",
                "4,TIPE-4",
                "4.5LT,4.5 LANTAI",
                "4BR,4BR",
                "4BR',4BR'",
                "4BR0,4BR",
                "4BR1,4BR'",
                "5,TIPE-5",
                "5BR,5 Bedrooms",
                "6,TIPE-6",
                "6CDS,6x15",
                "6HK,6x15",
                "6HOK,6x15",
                "6IRG1,6x15",
                "6IRG2,6x15",
                "6IRG3,6x15",
                "6IRR1,6x15",
                "6IRR2,6x15",
                "6IRR3,6x15",
                "6REG,6x15",
                "7,TIPE-7",
                "7CDS,7x15",
                "7HK,7x15",
                "7HOK,7x15",
                "7IRG1,7x15",
                "7IRG2,7x15",
                "7IRG3,7x15Irregular 3",
                "7IRR1,7x15",
                "7IRR2,7x15",
                "7IRR3,7x15",
                "7REG,7x15",
                "8,TIPE-8",
                "8CDS,8x15",
                "8HK,8x15",
                "8HOK,8x15",
                "8IRG1,8x15",
                "8IRG2,8x15",
                "8IRG3,8x15",
                "8IRR1,8x15",
                "8IRR2,8x15",
                "8IRR3,8x15",
                "8REG,8x15",
                "8STD,8x15",
                "A,TIPE-A",
                "A/112,TIPE-A/112",
                "A/136,TIPE-A/136",
                "A/218,TIPE-A/218",
                "A/RH,TIPE-A Rolling Hills",
                "A1,A1",
                "A112S,TIPE-A/112 Sudut",
                "A136s,TIPE-A/136 Sudut",
                "A2,A2",
                "A218S,TIPE-A/218 Sudut",
                "A23,2/3 STANDARD",
                "A2PES,A2 with PES",
                "A3,A3",
                "A33,3/3 STANDARD",
                "A34,3/4 STANDARD",
                "A3PES,A3 with PES",
                "A44,4/4 STANDARD",
                "A5PES,A5 with PES",
                "A6PES,A6 WITH PES",
                "A8,A8",
                "Aa,A-a",
                "AADG,Amaryllis A Design",
                "Ab,A-b",
                "ABC,A / B / C",
                "ABDG,Amaryllis B Design",
                "Ac,A-c",
                "ACDG,Amaryllis C Design",
                "Ad,A-d",
                "ADO,ADOLF",
                "AFF,AFFANDI",
                "AHU,Ruang AHU",
                "AHY,AHU HYPERMART",
                "AK,Area Komersial",
                "AK0,AKASAKA",
                "AK1,AKASAKA Sdt.1",
                "AL0,ALHAMBRA",
                "AL1,ALHAMBRA Sdt.",
                "ALA,ALABAMA",
                "ALBA,Alabama",
                "ALC,ALCALA (2Lt.)",
                "ALE,ALESANDRIAN MED",
                "ALI,ALICANTE",
                "ALMD,Alamanda",
                "ALMO,Almond",
                "ALN,ALESANDRIAN NEW",
                "ALORA,Alora",
                "ALSD,Alyssum Design",
                "ALU,ALUMERIA",
                "AM0,AMANDARI",
                "AM1,AMANDARI Sdt.1",
                "Ama,Amara",
                "AMB,AMBROSSE",
                "Ambe,Amber",
                "AMDG,The Amaryllis Design",
                "AME,AMETHYST",
                "AMR,AMBASSADOR (8x20)",
                "AMS,AMSTERDAM",
                "AN,ALFRED NOBEL",
                "ANB,ANTONIO BLANCO",
                "AND,ANDALUCIA",
                "ANT,ANTONIO BLANCO",
                "AP,Area Penunjang",
                "ARH,TIPE-A Rolling Hills",
                "ARS,ARIE SMITH",
                "ASA,MENARA ASIA",
                "ASH,ASHFORD",
                "ASL,ASHLAND",
                "ATA,Antena",
                "ATM,ATM CENTER",
                "AU0,St. AUBERT",
                "AV0,AVILA",
                "AV1,AVILA Sdt.",
                "AVA-A,Avara A",
                "AVA-B,Avara B",
                "AVAA,Avara A",
                "AVAB,Avara B",
                "AVI,AVIARA",
                "AZH,AZAHAR (2Lt.)",
                "B,Tipe-B",
                "B-1A,1 Bedroom",
                "B-1H,1 Bedroom",
                "B-1I,1 Bedroom",
                "B-1J,1 Bedroom",
                "B-1K,1 Bedroom",
                "B-1L,1 Bedroom",
                "B-2B,2 Bedroom",
                "B-2D,2 Bedroom",
                "B-2E,2 Bedroom",
                "B-2F,2 Bedroom",
                "B-2G,2 Bedroom",
                "B-3A,3 Bedroom",
                "B-3B,3 Bedroom",
                "B-3C,3 Bedroom",
                "B/112,TIPE-B/112",
                "B/136,TIPE-B/136",
                "B/218,TIPE-B/218",
                "B/RH,TIPE-B Rolling Hills",
                "B09,B9",
                "B1,B1",
                "B10,B10",
                "B10P,B10P",
                "B11,B11",
                "B112S,TIPE-B/112 Sudut",
                "B136S,TIPE-B/136 Sudut",
                "B2,B2",
                "B218S,TIPE-B/218 Sudut",
                "B3,B3",
                "B3-A,B3-A",
                "B3-B,B3-B",
                "B3-E,B3-E",
                "B3A,B3-A",
                "B3E,B3-E",
                "B4-C,B4-C",
                "B4-D,B4-D",
                "B4-F,B4-F",
                "B4-G,B4-G",
                "B4-H,B4-H",
                "B4-I,B4-I",
                "B4-L,B4-L",
                "B4-N,B4-N",
                "B4-O,B4-O",
                "B4F,B4-F",
                "B4G,B4-G",
                "B5,B5",
                "B5-K,B5-K",
                "B5-M,B5-M",
                "B6,B-6",
                "B6-J,B6-J",
                "B8,B8",
                "B8P,B8P",
                "B9,B-9",
                "B9P,B9P",
                "Ba,B-a",
                "BAL,BALE",
                "BAN,BANGKOK",
                "BAP,Battery Park",
                "BAR,BARLI",
                "Bb,B-b",
                "Bc,B-c",
                "BC1,B-c",
                "BDI,BLUE DIAMOND",
                "BEA,BEACON 3LT (KOM)",
                "BEB,BEBALI",
                "BEL,BELLAGIO",
                "BIL,BILYARD CENTER",
                "BL3.5,Balkon 3.5 LT",
                "BL4.5,Balkon 4.5LT",
                "BLA,BLANCA (1Lt.)",
                "BLS,Balai Serpong",
                "BM,Building Management",
                "BMB,Basar Mobil",
                "BMT,Badminton",
                "BOC,Bank Of China",
                "BOI,BOTTICELLI (3LT)",
                "BON,BONNET",
                "BOO,Book Store",
                "BOR,BOURBON",
                "BOS,BOSTON",
                "BOT,BOTTOCINO",
                "BOX,BORDEAUX",
                "BP,BLAISE PASCAL",
                "BRC,BARCELONA",
                "BRG,BARONG",
                "BRI,BRITTANY",
                "BRO,Brooklyn",
                "BRS,BARIS",
                "BSDG,Blossom Design",
                "BSL,BASSILIAN",
                "BSN,BASSENIAN",
                "BST,Book Store",
                "BTN,BIG TENANT",
                "BUC,BUCKINGHAM",
                "BV,Boulevard Vue",
                "BV1,BV1",
                "BV3,BV3",
                "BV5,BV5",
                "BV8,BV8",
                "BWDG,Broadway Design",
                "BWO,BRENTWOOD",
                "BYD,Bilyard",
                "C,TIPE-C",
                "C/112,TIPE-C/112",
                "C/136,TIPE-C/136",
                "C/RH,TIPE-C Rolling Hills",
                "C1,C1",
                "C11,C11",
                "C112S,TIPE-C/112 Sudut",
                "C11P,C11P",
                "C12,C12",
                "C136,TIPE-C/136 Sudut",
                "C2,C2",
                "C2A,C2-A",
                "C2B,C2-B",
                "C2C,C2-C",
                "C2D,C2-D",
                "C2D1,C2-D'",
                "C2F,C2-F",
                "C2F1,C2-F'",
                "C34,3/4 HOOK",
                "C3E,C3-E",
                "C3E1,C3-E'",
                "C3G,C3-G",
                "C3G1,C3-G'",
                "C3G1a,C3-G'a",
                "C3G1b,C3-G'b",
                "C3Ga,C3-Ga",
                "C3Gb,C3-Gb",
                "C3H,C3-H",
                "C3H1,C3-H'",
                "C3K,C3-K",
                "C3K1,C3-K'",
                "C3L,C3-L",
                "C3L1,C3-L'",
                "C4H,C4-H",
                "C4H1,C4-H'",
                "C4H1a,C4-H'a",
                "C4H1b,C4-H'b",
                "C4Ha,C4-Ha",
                "C4Hb,C4-Hb",
                "C4I,C4-I",
                "C4I1,C4-I'",
                "C4I1a,C4-I'a",
                "C4I1b,C4-I'b",
                "C4Ia,C4-Ia",
                "C4Ib,C4-Ib",
                "C4J,C4-J",
                "C4J1,C4-J'",
                "C4J1a,C4-J'a",
                "C4J1b,C4-J'b",
                "C4Ja,C4-Ja",
                "C4Jb,C4-Jb",
                "C4M,C4-M",
                "C4M1,C4-M'",
                "C6,C6",
                "C7,C7",
                "C7P,C7P",
                "C8,C8",
                "Ca,C-a",
                "CA0,CATTELYA",
                "CA1,CATTELYA sdt.1",
                "CA3,CATTELYA Sdt.",
                "CAB,CAMBRIO",
                "CAD,CADIZ (2Lt.)",
                "CAL,CALIFORNIAN MED.",
                "CAM,CAMBRIDGE",
                "CAN,CATANIAN NEW",
                "CAP,CAPRI",
                "CAR,CARARA",
                "CAS,Casablanca (2.5 Lt)",
                "CAT,CATANIAN MED",
                "Cb,C-b",
                "CDC,CASA de la CORUNA",
                "CDN,CENDANA",
                "CDPK,CITY-DHARMAWANGSA-POOL-KEMANG",
                "CDS,CASA de SEVILLA",
                "CDV,CASA de VALENCIA",
                "CDY,CHARDONNAY",
                "CEB,CEBU",
                "CEDA,Cedar",
                "CEN,CENTURY",
                "CEZ,CEZANNE (2LT)",
                "CH2,COLOMBUS 2LT (HUN)",
                "CH3,COLOMBUS 3LT (HUN)",
                "CHE,CHELSEA",
                "CHI,CHIANGMAI",
                "CHI1,Chicago",
                "CHO,Club House",
                "CHRY,Cherry Design",
                "CIG,Cigliano (2.5 Lt)",
                "CIN,Cinema",
                "CK2,COLOMBUS 2LT (KOM)",
                "CL,Columbarium",
                "CLA,CLARET",
                "CLD,CALIDA (1Lt.)",
                "CLE,CLEVELAND",
                "CLEMA,Clematis",
                "CLO,Casual Leasing Outdoor",
                "CLVR,Clover",
                "CO0,CORDOBA",
                "CO1,CORDOBA Sdt.",
                "COA,Coapa (3.5 Lt)",
                "COC,CONCORDE (3LT)",
                "CON,CORNING",
                "COR,CORNELLA",
                "COR1,Cortes (2.5 Lt)",
                "COX,CONCORDE (3LT)",
                "CQY,CLARKE QUAY",
                "CR0,CHANTARA",
                "CR1,CHANTARA Sdt.1",
                "CRD,CORONADO",
                "CRN,CORUNNA (2Lt.)",
                "CRV,CARAVEL",
                "CRY,CRYSTAL",
                "CSC,CORSICA",
                "CT1,CIATER sdt.1",
                "CT2,CIATER sdt.2",
                "CTDHP,City-Dhamawangsa-Pool",
                "CTN,CATALINA",
                "CTR,CIATER",
                "CTU,CHATEAU",
                "CUB,CUBIC",
                "CVDG,The Clove Design",
                "CWS,CAR WASH",
                "CWY,CAUSE WAY",
                "CZC,CUBIC ZIRCONIA COR.",
                "CZI,CUBIC ZIRCONIA",
                "D,TIPE-D",
                "D/123,TIPE-D/123",
                "D/RH,TIPE-D Rolling Hills",
                "D10,D10",
                "D123S,TIPE-D/123 Sudut",
                "D3,D3",
                "D5,D5",
                "D6,D-6",
                "D9,D9",
                "Da,D-a",
                "DA1,DAGO sdt.1",
                "DA2,DAGO sdt.2",
                "DAG,DAGO",
                "DAI,DAICHI",
                "DAK,DAKE",
                "DAR,Dario (8x18)",
                "DAU,DAURADA (1Lt.)",
                "Db,D-b",
                "DEN,DENPASAR",
                "DEZ,DE ZENTJE",
                "DFDL,Dafodil",
                "DHG,DEN HAAG",
                "DHPOK,Dhamawangsa-Pool-Kemang",
                "DLF,DELFIN",
                "DOO,DOO YEWAARD",
                "DSJ,Dunia Salju",
                "DUL,DULLAH",
                "DVC,DA VINCI",
                "E,TIPE-E",
                "E - 3,E - 3I",
                "E-1A,1BR Suite-Series",
                "E-1B,1BR Suite-Series",
                "E-2C,2BR Suites-Series",
                "E-2D,2BR Suites-Corner",
                "E-2E,2BR Suite-Series",
                "E-2F,2BR Suite-Series",
                "E-2G,2BR Suites-Series",
                "E-3H,3BR Suite-Corner",
                "E-3I,3BR Suite-Corner",
                "E/123,TIPE-E/123",
                "E123S,TIPE-E/123 Sudut",
                "E2A,E2-A",
                "E2A1,E2-A'",
                "E2B,E2-B",
                "E2B1,E2-B'",
                "E2B2,E2-B''",
                "E2B3,E2-B'''",
                "E2C,E2-C",
                "E2C1,E2-C'",
                "E2H,E2-H",
                "E2I,E2-I",
                "E2J,E2-J",
                "E3A,E3-A",
                "E3D,E3-D",
                "E3D1,E3-D'",
                "E3D2,E3-D''",
                "E3D3,E3-D'''",
                "E3E,E3-E",
                "E3E1,E3-E'",
                "E3E1a,E3-E'a",
                "E3E1b,E3-E'b",
                "E3Ea,E3-Ea",
                "E3Eb,E3-Eb",
                "E3K,E3-K",
                "E3L,E3-L",
                "E3L1,E3-L'",
                "E44,4/4 HOOK",
                "E4B,E4-B",
                "E4B1,E4-B'",
                "E4C,E4-C",
                "E4C1,E4-C'",
                "E4F,E4-F",
                "E4F1,E4-F'",
                "E4F1a,E4-F'a",
                "E4F1b,E4-F'b",
                "E4Fa,E4-Fa",
                "E4Fb,E4-Fb",
                "E4G,E4-G",
                "E4G1,E4-G'",
                "E4G1a,E4-G'a",
                "E4G1b,E4-G'b",
                "E4Ga,E4-Ga",
                "E4Gb,E4-Gb",
                "E7,E-7",
                "EC,Education Center",
                "EDI,EDINBURG",
                "ELASA,Elasa",
                "ELISA,Elisa",
                "ELISE,Elise",
                "ELV,Elvio (8X20)",
                "EMRD,Emerald Design",
                "ES0,ESMERALDA",
                "ES1,ESMERALDA Sdt.1",
                "ESC,Escorial (4.5 Lt)",
                "ESSC,Essence",
                "EVRT,Everest",
                "F,TIPE-F",
                "F/123,TIPE-F/123",
                "F/RH,TIPE-F Rolling Hills",
                "F1,TIPE-F1",
                "F123S,TIPE-F/123 Sudut",
                "Fa,F-a",
                "Fb,F-b",
                "FLORE,Florencia",
                "FOO,Food Court Counter",
                "FRE,FRENCH MED.",
                "FSL,FUTSAL",
                "G,TIPE-G",
                "G-1A,1 Bedroom",
                "G-1B,1 Bedroom",
                "G-1C,1 Bedroom",
                "G-1D,1 Bedroom",
                "G-1E,1 Bedroom",
                "G-1F,1 Bedroom",
                "G-1G,1 Bedroom",
                "G-1H,1 Bedroom",
                "G-2A,2 Bedroom",
                "G-2B,2 Bedroom",
                "G-2C,2 Bedroom",
                "G-3A,3 Bedroom",
                "G-3B,3 Bedroom",
                "G-3C,3 Bedroom",
                "G-3D,3 Bedroom",
                "G1,G1",
                "G2,G2",
                "G2A,RG2-A",
                "G3,G3",
                "G3B1a,RG3-B'a",
                "G3B1b,RG3-B'b",
                "G3Ba,RG3-Ba",
                "G3Bb,RG3-Bb",
                "G3C1a,RG3-C'a",
                "G3C1b,RG3-C'b",
                "G3Ca,RG3-Ca",
                "G3Cb,RG3-Cb",
                "G3Ea,RG3-Ea",
                "G3Eb,RG3-Eb",
                "G3Fa,RG3-Fa",
                "G3Fb,RG3-Fb",
                "G4A,RG4-A",
                "G4Da,RG4-Da",
                "G4Db,RG4-Db",
                "G4F1a,RG4-F'a",
                "G4F1b,RG4-F'b",
                "G4F1c,RG4-F'c",
                "G4Fa,RG4-Fa",
                "G4Fb,RG4-Fb",
                "G4Fc,RG4-Fc",
                "G4G1,RG4-G'b",
                "G4G1a,RG4-G'a",
                "G4G1b,RG4-G'b",
                "G4G1c,RG4-G'c",
                "G4Ha,RG4-Ha",
                "G4Hb,RG4-Hb",
                "G4Hc,RG4-Hc",
                "G5,G5",
                "G5Ea,RG5-Ea",
                "G5Eb,RG5-Eb",
                "G5Ec,RG5-Ec",
                "G5Ga,RG5-Ga",
                "G5Gb,RG5-Gb",
                "G5Gc,RG5-Gc",
                "G5Ia,RG5-Ia",
                "G5Ib,RG5-Ib",
                "G5Ic,RG5-Ic",
                "G5Id,RG5-Id",
                "G8,G8",
                "GAR,GARNIER (3LT)",
                "GAU,GAUGIN (3LT)",
                "GAX,GARNIER (3LT)",
                "GB,GRAHAM BELL",
                "GDDG,GoldenRod Design",
                "GDG,Gudang",
                "GDH,Gudang Hypermart",
                "GEN,Ruang Genset",
                "GEO,GEORGIA",
                "GHY,GUDANG HYPERMART",
                "GIA,GIANYAR",
                "GIN,GINZA",
                "GKT,Gokart",
                "GLA,GLAMES",
                "GLG,GUDANG LOGISTIK",
                "GRA,GRANADA",
                "GRA1,Gracia (2.5 Lt)",
                "GRD,Grande (2.5 Lt)",
                "GRDG,The Green Design",
                "GRE,GREECE MED.",
                "GRN,GRANDE MED. (RMH)",
                "GSG,GEDUNG SERBA GUNA",
                "GTH,GREASE-TRAP HYPER",
                "GTO,GEORGETOWN",
                "GWT,Ground Water",
                "H,TIPE-H",
                "HAM,HAMPTON",
                "HDF,HIGH DELFIN",
                "HEI,HEIAN",
                "HES,HEIAN Sdt.",
                "HMS01,Urban Homes Lantai 1",
                "HMS02,Urban Homes Lantai 2",
                "HMS03,Urban Homes Lantai 3",
                "HMS05,Urban Homes Lantai 5",
                "HMS06,Urban Homes Lantai 6",
                "HMS07,Urban Homes Lantai 7",
                "HMS08,Urban Homes Lantai 8",
                "HMS09,Urban Homes Lantai 9",
                "HMS10,Urban Homes Lantai 10",
                "HMS11,Urban Homes Lantai 11",
                "HMS12,Urban Homes Lantai 12",
                "HMS15,Urban Homes Lantai 15",
                "HMS16,Urban Homes Lantai 16",
                "HMS17,Urban Homes Lantai 17",
                "HMS18,Urban Homes Lantai 18",
                "HMS19,Urban Homes Lantai 19",
                "HMS20,Urban Homes Lantai 20",
                "HMS21,Urban Homes Lantai 21",
                "HMS22,Urban Homes Lantai 22",
                "HMS23,Urban Homes Lantai 23",
                "HMS25,Urban Homes Lantai 25",
                "HMS26,Urban Homes Lantai 26",
                "HMS27,Urban Homes Lantai 27",
                "HMS28,Urban Homes Lantai 28",
                "HMS29,Urban Homes Lantai 29",
                "HMS30,Urban Homes Lantai 30",
                "HMS31,Urban Homes Lantai 31",
                "HMS32,Urban Homes Lantai 32",
                "HMS33,Urban Homes Lantai 33",
                "HMS35,Urban Homes Lantai 35",
                "HMS36,Urban Homes Lantai 36",
                "HMS37,Urban Homes Lantai 37",
                "HMS38,Urban Homes Lantai 38",
                "HMS39,Urban Homes Lantai 39",
                "HMSSG,Urban Homes Lantai Sky Garden",
                "HMSSS,Urban Homes Lantai Sky Suite",
                "HOF,HOFFKER",
                "HOL,HOLLYROOD",
                "HOO,HOOK",
                "HUD,Hudson",
                "HWS,Houseware Shop",
                "HYP,Hypermart",
                "I-1E,1 Bedroom",
                "I-1F,1 Bedroom",
                "I-1G,1 Bedroom",
                "I-1H,1 Bedroom",
                "I-2C,2 Bedroom",
                "I-2D,2 Bedroom",
                "I-2H,2 Bedroom",
                "I-2I,2 Bedroom",
                "I-3A,3 Bedroom",
                "I-3B,3 Bedroom",
                "I2-F,I2-F",
                "I2-F',I2-F'",
                "I2-F1,I2-F'",
                "I2A,I2-A",
                "I2B,I2-B",
                "I2B1,I2-B'",
                "I2C,I2-C",
                "I2D,I2-D",
                "I2D1,I2-D'",
                "I2E,I2-E",
                "I2E1,I2-E'",
                "I2F,I2-F",
                "I2F1,I2-F'",
                "I3-G',I3-G'",
                "I3-G1,I3-G'",
                "I3-H,I3-H",
                "I3-H',I3-H'",
                "I3-H1,I3-H'",
                "I3GA,I3-GA",
                "I3GA1,I3-GA'",
                "I3GB,I3-GB",
                "I3GB1,I3-GB'",
                "I3HA,I3-HA",
                "I3HA1,I3-HA'",
                "I3HB,I3-HB",
                "I3HB1,I3-HB'",
                "I3IA,I3-IA",
                "I3IB,I3-IB",
                "I4-J,I4-J",
                "I4J,I4-J",
                "I4JA,I4-JA",
                "I4JA1,I4-JA'",
                "I4JB,I4-JB",
                "I4JB1,I4-JB'",
                "I4JC,I4-JC",
                "I4JC1,I4-JC'",
                "I4KA,I4-KA",
                "I4KA1,I4-KA'",
                "I4KB,I4-KB",
                "I4KB1,I4-KB'",
                "I4KC,I4-KC",
                "I4KC1,I4-KC'",
                "I5LA,I5-LA",
                "I5LB,I5-LB",
                "I5LC,I5-LC",
                "I5LD,I5-LD",
                "IBI,IBIZA (2Lt.)",
                "IGN,Ignacio (8x18var)",
                "INC,Incenio (9x18var)",
                "IRSH,Irish Design",
                "IRV,IRVINGTON",
                "ISA,Isabela (3.5 Lt)",
                "It1A,It1-A",
                "It1B,It1-B",
                "It1D,It1-D",
                "It2D,It2-D",
                "ITA,ITALIAN MED",
                "ItDA,ItD-A",
                "ITN,ITALIAN NEW",
                "ItPB,ItP-B",
                "ItSA,ItS-A",
                "ItSB,ItS-B",
                "ITW,ITAEWON",
                "IVY,Ivy Design",
                "JAD,JADE",
                "JBR,JULIA BRIDAL",
                "JDE,JADE (TownHouse)",
                "JEI,JEIHAN",
                "JMDG,Jasmine Design",
                "JU0,St. JULIEN",
                "KA0,KING ARTHUR",
                "KA1,KING ARTHUR SdT.",
                "KALI,Kalista",
                "KAM,KAMAKURA",
                "KAMI,Kamilia",
                "KANI,Kaniel",
                "KANIS,Kaniel Spesial",
                "KAV,KAVLING",
                "KAVCD,KavlingCuldesac",
                "KAVHK,KavlingHoek",
                "KC0,KING CHARLES",
                "KCDP,KEMANG -CITY-DHARMAWANGSA-Pool",
                "KCDS,KAVLING",
                "KEC,KECAK",
                "KEN,KENSINGTON",
                "KG0,KING GEORGE",
                "KH0,KING HENRY",
                "KHOK,KAVLING",
                "KIRG2,Kavling",
                "KIRG3,Kavling",
                "KIRR2,KAVLING",
                "KIRR3,KAVLING",
                "KJ0,KING JAMES",
                "KJ1,KING JAMES Sdt.",
                "KK0,KING CONSTANTINE",
                "KK1,KING CONSTANTINE Sdt",
                "KM0,KAMAKURA",
                "KM1,KAMAKURA Sdt.1",
                "KML,Kantor Marketing Leasing",
                "KOE,KOEMPUL",
                "KOR,KORI",
                "KOW,KOWLOON",
                "KP,KANTOR PARKIR",
                "KR0,KING RICHARD",
                "KRK,Karaoke",
                "KSH,Kantor Shopshouse",
                "KUL,KUL-KUL",
                "KUT,KUTA",
                "KVHK,Kavling",
                "L1,L1",
                "L2,L2",
                "L3,L3",
                "L5,L5",
                "L6,L6",
                "L8,L8",
                "LA0,LAELIA",
                "LA1,LAELIA sdt.1",
                "LA3,LAELIA Sdt.",
                "LADE,Ladera",
                "LAG,LAGONI",
                "LAK,Lake Side Rest",
                "LAV,LAVERRA",
                "LAVE,Lavender",
                "LDH,Loading Dock Hypermart",
                "LDM,Loading Dock Matahari",
                "LE1,LEMBANG sdt.1",
                "LE2,LEMBANG sdt.2",
                "LEG,LEGIAN",
                "LEM,LEMBANG",
                "LEP,LEMPAD",
                "LEX,Lexington",
                "LGO,LEGONG",
                "LHY,Lift Hypermart",
                "LIB,Liberty",
                "LIDG,Longisland Design",
                "LILA,Lilac Design",
                "LIP,Lippo Bank",
                "LJL,LA JOLLA",
                "LMD,Lift MDS",
                "LMY,LE MAYEUR",
                "LN0,LANNA",
                "LN1,LANNA Sdt.1",
                "LNDG,Luna Design",
                "LOB,Lobby Cinema",
                "LOC,LOCATELLI",
                "LOH,Lobby Hotel",
                "LOI,LOUISVILLE",
                "LOI1,LongIsland",
                "LON,London",
                "LOU,LOUVRE (3LT)",
                "LOV,LOUVRE (2LT)",
                "LR0,St. LAURENT",
                "LRDG,Leora Design",
                "LTB,Lapangan Tembak",
                "LTDG,Lexington Design",
                "LTM,Lapangan Tenis Meja",
                "LVR,LOUVER",
                "M-1G,1BR",
                "M-1G',1BR",
                "M-1G1,1BR",
                "M-1H,1BR",
                "M-2C,2BR",
                "M-2D,2 Bedroom",
                "M-2E,2BR",
                "M-2F,2BR",
                "M-2K,2BR",
                "M-2L,2BR",
                "M-2M,2BR",
                "M-3A,3BR",
                "M-3A',3BR",
                "M-3A1,3BR",
                "M-3B,3BR",
                "M-4I,4BR",
                "M-4J,4BR",
                "M3A,M-3A",
                "MA-2A,2 Bedroom",
                "MA-2B,2 Bedroom",
                "MA-2C,2 Bedroom",
                "MA-3A,3 Bedroom",
                "MA-3B,3 Bedroom",
                "MA-4A,4 Bedroom",
                "MA-4B,4 Bedroom",
                "MA-4C,4 Bedroom",
                "MA0,St. MARTIN",
                "MAD,Madison",
                "MAG,MAGROLIA",
                "MAI,MAIZONETTE",
                "MAK,MAKATI",
                "MAL,MALIBU",
                "MAN,Manhattan",
                "MAR,MARFIORE",
                "MARO,Magrolia",
                "MAT,MATISSE (2LT)",
                "MAT1,Matahari Supermarket",
                "MB-2A,3 Bedroom",
                "MB-2B,3 Bedroom",
                "MB-2C,2 Bedroom",
                "MB-2D,2 Bedroom",
                "MB-2E,2 Bedroom",
                "MB-2F,2 Bedroom",
                "MB-2G,2 Bedroom",
                "MB-2H,2 Bedroom",
                "MB-2I,2 Bedroom",
                "MB-3A,3 Bedroom",
                "MB-3B,3 Bedroom",
                "MCD,Mc Donalds",
                "MDS,Matahari Dept. Store",
                "ME,Ruang ME",
                "MEI,MEIJI",
                "MEL,MELROSE",
                "MES,MEIJI Sdt.",
                "MGDG,Magnolia Design",
                "Mgn,Magnolia",
                "MHDG,Manhattan Design",
                "MHY,R. MESIN HYPERMART",
                "MI0,St. MICHEL",
                "MI1,St. MICHEL Sdt.1",
                "MIR,MIRO (3LT)",
                "MJL,Toko Majalah",
                "ML0,MALLORCA",
                "ML1,MALLORCA Sdt.1",
                "MLC,MELCO",
                "MLO,MICHAELANGELO",
                "MNE,MONET (3LT)",
                "MNT,MONTICELLO",
                "MON,MONTEREY (RMH)",
                "MON1,Monterrey (3.5 Lt)",
                "MOR-A,A",
                "MOR-B,B",
                "MOR-C,C",
                "MOR-D,D",
                "MOS,MOSELLE",
                "MOZ,MOZAIC",
                "MPLE,THE MAPLE",
                "MR,Mural",
                "MR0,MARBELLA",
                "MRG,MARGOLIA",
                "MRK,MARKEN",
                "MRN,MARINA",
                "MS-1A,1 Bedroom",
                "MS-2A,2 Bedroom",
                "MS-2B,2 Bedroom",
                "MS-2C,2 Bedroom",
                "MS-2D,2 Bedroom",
                "MSDG,Madison Design",
                "MSM,Matahari Supermarket",
                "N-1A,1 Bedroom Premium",
                "N-1B,1 Bedroom",
                "N-1C,1 Bedroom",
                "N-1D,1 Bedroom",
                "N-1E,1 Bedroom",
                "N-2A,2 Bedroom Premium",
                "N-2B,2 Bedroom Premium",
                "N-2C,2 Bedroom",
                "N-2D,2 Bedroom",
                "N-2E,2 Bedroom",
                "N-2F,2 Bedroom",
                "N-3A,3 Bedroom",
                "N-3B,3 Bedroom",
                "NAR,NARA",
                "NAS,NARA Sdt.",
                "NBDG,New Blossom Design",
                "NC0,NEW CIATER",
                "NC1,NEW CIATER Sdt.1",
                "NC2,NEW CIATER Sdt.2",
                "NCLVR,New Clover",
                "ND0,NEW DAGO",
                "ND1,NEW DAGO Sdt.1",
                "ND2,NEW DAGO Sdt.2",
                "NESSC,New Essence",
                "NEVRT,New Everest",
                "NEW,New York",
                "NGGD,New Green Garden Design",
                "NI0,NIKKO",
                "NI1,NIKKO Sdt.1",
                "NIDG,Nirwana Design",
                "NIK,NIKKO (Ruko)",
                "NJDG,The New Jasmine Design",
                "NL0,NEW LEMBANG",
                "NL1,NEW LEMBANG Sdt.1",
                "NL2,NEW LEMBANG Sdt.2",
                "NON,KAVLING ONLY",
                "NPDG,New Primrose Design",
                "Nr1A,studio + 1 bath[29.4 m2]",
                "Nr1B,studio + 1 bath[36.6 m2]",
                "Nr1C,studio + 1 bath[38.3 m2]",
                "Nr1D,1 bed + 1 bath[44.1 m2]",
                "Nr1E,1 bed + 1 bath[47.1 m2]",
                "Nr1F,studio + 1 bath[48.5 m2]",
                "Nr1G,1 bed + 1 bath[57.8 m2]",
                "Nr2H,2 bed + 1 bath (inc den)[77.7 m2]",
                "Nr2I,2 bed + 1 bath (inc den)[83.2 m2]",
                "Nr2J,2 bed + 2 bath[88.8 m2]",
                "Nr3K,3 bed + 2 bath (inc den)[116.9 m2]",
                "Nr3L,3 bed + 2 bath (inc den)[125.8 m2]",
                "Nr3M,3 bed + 3 bath[132.3m2]",
                "Nr3N,3 bed + 2 bath (inc den) Garden[116.9 m2]",
                "Nr3O,3 bed + 2 bath (inc den) + Garden[116.9 m2]",
                "Nr3P,3 bed + 2 bath + garden[119.8 m2]",
                "Nr3Q,3 bed + 2 bath + garden[134.1m2]",
                "NRD,NEW ROAD",
                "OA0,OAKPARK",
                "OA1,OAKPARK Sdt.",
                "OADG,Orchard Design",
                "OADGA,Orchard Design A",
                "OADGB,Orchard Design B",
                "OADGC,Orchard Design C",
                "OCDG,Orchid Design",
                "OCDGA,Orchid Design A",
                "OCDGB,Orchid Design B",
                "OLVE,Olive",
                "ONX,ONYX",
                "OPL,OPAL",
                "ORC,ORCHARD",
                "ORH,ORCHARD HILL",
                "ORI,OAKRIDGE",
                "OS,Orchard Sky",
                "OT0,OTLA (1LT)",
                "OT1,OTLA Sdt. (1LT)",
                "OV,Orchard Vue",
                "OXF,OXFORD",
                "P-1I,1 Bedroom",
                "P-1J,1 Bedroom",
                "P-1K,1 Bedroom",
                "P-1L,1 Bedroom",
                "P-1M,1 Bedroom",
                "P-1N,1 Bedroom",
                "P-1O,1 Bedroom",
                "P-1P,1 Bedroom",
                "P-2C,2 Bedroom",
                "P-2D,2 Bedroom",
                "P-2E,2 Bedroom",
                "P-2F,2 Bedroom",
                "P-2G,2 Bedroom",
                "P-2H,2 Bedroom",
                "P-3A,3 Bedroom",
                "P-3B,3 Bedroom",
                "P-3Q,3 Bedroom",
                "P1,P1",
                "P1-L,P1-L",
                "P10,Parkir P10",
                "P2,Parkir P2",
                "P3,P3",
                "P4,Parkir P4",
                "P5,P5",
                "P6,Parkir P6",
                "P7, Parkir P7",
                "P8,Parkir P8",
                "P9,Parkir P9",
                "PA,PA",
                "PA1a,PA-1",
                "PA1b,PA'-1",
                "PA2,Palma (2.5 Lt)",
                "PA2a,PA-2",
                "PA2b,PA'-2",
                "PAL,PALMA (2Lt.)",
                "PAL1,Palma (3.5 Lt)",
                "PAR,Paris",
                "PAS,PASADENA",
                "PAS1,Paseo (4.5 Lt)",
                "PAU,PAULIDES",
                "PB,PB",
                "PB'1,PB'-1",
                "PB1,Parkir PB1",
                "PB1a,PB-1",
                "PB1b,PB'-1",
                "PB2,Parkir PB2",
                "PB2a,PB-2",
                "PB2b,PB'-2",
                "PC,PC",
                "PD1,PD-1",
                "PD2,PD-2",
                "PE,Private Estate Tembok",
                "PEN,PENDET",
                "PER,PERADA",
                "PER1,Perinorte (4.5 Lt)",
                "PES,PESCADERO",
                "PG,Private Estate Patung",
                "PH,Penthouse",
                "PI,Bong Pi",
                "PI0,St. PIERRE",
                "PIN,PINUS",
                "PINE,Pine",
                "PINO,Pianosa",
                "PL0,PLANNAR (1LT)",
                "PL1,PLANNAR Sdt. (1LT)",
                "PLZ,PALAZZO",
                "POL,POLENG",
                "PP,Peak Estate",
                "PRDG,Primrose Design",
                "PRI,PRINCETON",
                "PRS,PRISTINE (6x15)",
                "PS,Private Estate Shrubs",
                "PT,Private Terrace",
                "PUR,PURI",
                "PV,Paviliun",
                "PWY,PARK WAY",
                "PWZ,PARK WAY",
                "QH2,QUINCY 2LT (HUN)",
                "QH3,QUINCY 3LT (HUN)",
                "QK2,QUINCY 2LT (KOM)",
                "QK3,QUINCY 3LT (KOM)",
                "R1C,R1-C",
                "R1C1,R1-C'",
                "R1D,R1-D",
                "R1G,R1-G",
                "R1G1,R1-G'",
                "R1H,R1-H",
                "R1O,R1-O",
                "R1P,R1-P",
                "R1R,R1-R",
                "R1S,R1-S",
                "R1U,R1-U",
                "R2A,R2-A",
                "R2B,R2-B",
                "R2B1,R2-B'",
                "R2E,R2-E",
                "R2F,R2-F",
                "R2I,R2-I",
                "R2I1,R2-I'",
                "R2J,R2-J",
                "R2K,R2-K",
                "R2L,R2-L",
                "R2L1,R2-L'",
                "R2M,R2-M",
                "R2N,R2-N",
                "R2Q,R2-Q",
                "R2T,R2-T",
                "R2V,R2-V",
                "R2W,R2-W",
                "R3C,R3-C",
                "R3C1,R3-C'",
                "R3C1a,R3-C'a",
                "R3C1b,R3-C'b",
                "R3Ca,R3-Ca",
                "R3Cb,R3-Cb",
                "R3E,R3-E",
                "R3F,R3-F",
                "R4D,R4-D",
                "R4Da,R4-Da",
                "R4Db,R4-Db",
                "R4G,R4-G",
                "R4G1,R4-G'",
                "R4H,R4-H",
                "R4I,R4-I",
                "R4L,R4-L",
                "R5J,R5-J",
                "R5K,R5-K",
                "RAF,RAFFLES",
                "RAP,RAPHAEL (3LT)",
                "RBY,RUBY",
                "RDWN,Red Dawn",
                "REC1,RECITO (2bd)",
                "REC2,RECITO' (2bd)",
                "REG1,REGATTA (3bd)",
                "REG2,REGATTA' (3bd)",
                "REM,REMY (1bd)",
                "REN,RENOIR (2LT)",
                "REN1,RENOVO (2bd)",
                "RES,Resto Square",
                "RET1,RETRO (1bd)",
                "RET2,RETRO' (1bd)",
                "REV1,REVA (2bd)",
                "REV2,REVA' (2bd)",
                "RFDG,Rafflesia Design",
                "RG3C1,RG3C1b",
                "RG3Ca,RG3-Ca",
                "RG3Cb,RG3-Cb",
                "RG3La,RG3-La",
                "RG3Lb,RG3-Lb",
                "RG4-D,CTDHPO",
                "RG4A,RG4-A",
                "RG4Da,RG4-Da",
                "RG4Db,RG4-Db",
                "RG4G1,RG4-G'a",
                "RG4Ga,RG4-Ga",
                "RG4Gb,RG4-Gb",
                "RG4Gc,RG4Gc",
                "RG4J,RG4-Ja",
                "RG4J1,RG4-J'",
                "RG4Ja,RG4-Ja",
                "RG4Jb,RG4-Jb",
                "RG4Jc,RG4-Jc",
                "RG4K4,RG4-Kc",
                "RG4Ka,RG4-Ka",
                "RG4Kb,RG4-Kb",
                "RG4Kc,RG4-Kc",
                "RG5Ha,RG5-Ha",
                "RG5Hb,RG5-Hb",
                "RG5Hc,RG5-Hc",
                "RG5Ia,RG5-Ia",
                "RG5Ib,RG5-Ib",
                "RG5Ic,RG5-Ic",
                "RG5Ka,RG5-Ka",
                "RG5Kb,RG5-Kb",
                "RG5Kc,RG5-Kc",
                "RG5Kd,RG5-Kd",
                "RIC,RICHFIELD",
                "RIO,RIONA (1bd)",
                "RIT,RITZ (3LT)",
                "RIV,RIVIERA MED.",
                "RIZ,RITZ (2LT)",
                "RK1LT,Ruko 1 Lantai",
                "RK2LT,Ruko 2 Lantai",
                "ROD,RODEO",
                "ROS,ROSENBURG",
                "ROT,ROTERDAM",
                "RSDG,RoseWood Design",
                "RSL,RUSSEL",
                "RT,Roof Top",
                "RUA,Ruang Utilitas MDS",
                "RUK,Ruko South (2 Lt)",
                "RUKA,Ruko A",
                "RUKB,Ruko B",
                "RUKC,Ruko C",
                "RUKD,Ruko D",
                "RUKE,Ruko E",
                "RUS,RUSLI",
                "RVR1,REVERE (2bd)",
                "S-1F,S-1F",
                "S-1G,S-1G",
                "S-1H,S-1H",
                "S-2C,S-2C",
                "S-2D,2 Bedroom",
                "S-2E,S-2E",
                "S-2I,2 bedroom",
                "S1B,S-1B",
                "S1D,S-1D",
                "S23,2/3 ATAU 3/3 STANDAR",
                "S2C,S-2C",
                "S2E,S-2E",
                "S2F,S-2F",
                "S34,3/4 ATAU 4/4 STANDAR",
                "SAD,SADALI",
                "SAK,SAKA",
                "SAL,SALISBURY",
                "SAN,SANTIAGO",
                "SAP,SAPPHIRE",
                "SAU,SAUSALITO",
                "SAV,Saverio (10x25)",
                "SB,Single Burial",
                "SBR,SANTA BARBARA",
                "SC0,SANTA CATERINA",
                "SC1,SANTA CATERINA Sdt.",
                "SCR,SANTA CRUZ (1Lt.)",
                "SD0,SAN DOMENICO",
                "SD1,SAN DOMENICO Sdt.",
                "SD4.5,Sudut 4.5LT",
                "SDH,Sekolah Dian Harapan",
                "SEV,SEVILLA",
                "SF,Sarkofagus",
                "SG1,SAN GERIMIA (3LT)",
                "SG2,SAN GERIMIA (3LT)",
                "SGI,SAN GIOVANNI (2LT)",
                "SGO,SAN GIOCOMO (3LT)",
                "SGR,SAN GIORGIO (3LT)",
                "SH0,SHUTTER (2LT)",
                "SHI,SHINJUKU",
                "SHY,Service Hypermart",
                "SI,Semi Bong Pi",
                "SKI,SKIBO",
                "SLT,SOLITAIRE",
                "SM,Salon Mobil",
                "SMA,SAN MARCO (3LT)",
                "SMC,SANTA MONICA",
                "SMPPA,Area Service MPPA",
                "SN,Single Burial Non Paket",
                "SNK,SUNGKAI",
                "SODG,Shop Office Design",
                "SOE,SOEDIBIO",
                "SOL,SOLVANG",
                "SP,Semi Private",
                "SP1,Super Penthouse 1",
                "SP2,Super Penthouse 2",
                "SP3,Super Petnhouse 3",
                "SP5,Super Petnhouse 5",
                "SP8,Super Petnhouse 8",
                "SPA,SPANISH MED",
                "SPH,Super Penthouse",
                "SPL,Sekolah Pelita Harapan",
                "SPM,SUPERMAL",
                "SPP,Super Penthouse",
                "SRC1,SUPERIOR RECITO (2bd)",
                "SRC2,SUPERIOR RECITO' (2bd)",
                "SRG1,SUPERIOR REGATTA (3bd)",
                "SRG2,SUPERIOR REGATTA' (3bd)",
                "SRN1,SUPERIOR RENOVO (2bd)",
                "SRO,SAN ROCCO (2LT)",
                "SRR1,SUPERIOR REVERE (2bd)",
                "SRT1,SUPERIOR RETRO (1bd)",
                "SRT2,SUPERIOR RETRO' (1bd)",
                "SRV1,SUPERIOR REVA (2bd)",
                "SRV2,SUPERIOR REVA' (2bd)",
                "SS,Semi Private Estate Shrub",
                "SSA,SAN SALVATORE (2LT)",
                "SSB,SAN SEBASTIAN (2LT)",
                "SSF,Superstar Fitness",
                "SSP,Signature Penthouse",
                "ST3.5,Standard 3.5 LT",
                "ST4.5,Standard 4.5LT",
                "STD,STANDARD",
                "STF,STARTFORD",
                "STI,STIRLING",
                "STM,STREAM",
                "STR,STRAUSSER",
                "SUN,SUNSET",
                "SVDG,Shop Office Valerian Design",
                "SZA,SAN ZACCARIA (3LT)",
                "SZN,SAN ZANIPOLO (3LT)",
                "T1,T1",
                "T106,TIPE 106",
                "T2,T2",
                "T22,Tipe 22",
                "T27,Tipe 27",
                "T29,Tipe 29",
                "T3,T3",
                "T325,TYPE 325",
                "T34,3/4 ATAU 4/4 HOOK",
                "T36,Tipe 36",
                "T399,TYPE 399",
                "T3A,T3A",
                "T3B,T3B",
                "T5,T5",
                "T6,T6",
                "T8,T8",
                "T8A,T8A",
                "T8B,T8B",
                "TADG,The Alessandra Design",
                "TDM,Tangga Darurat MPPA",
                "TE0,TERRACE (2LT)",
                "TE1,TERRACE Sdt. (2LT)",
                "TE2,TERRACE (2LT/Ops.1)",
                "TEN,TENGAH",
                "TER,TERRAZIO",
                "THM,THEOMEIER",
                "TIA,TIARA",
                "TIM,TIME ZONE",
                "TL0,TALIESIN",
                "TL1,TALIESIN Sdt.",
                "TOK,Tokyo",
                "TOP,TOPENG",
                "TPC,TEH POCI",
                "TRA,TRAVERTIN",
                "TRI,TRIVIAL (7x18)",
                "TRU,TRUBUS",
                "TU0,THUNIA",
                "TU1,THUNIA Sdt.1",
                "TUS,TUSCANY",
                "TVO,Trivio (7x20)",
                "TYP-A,A",
                "TYP-B,B",
                "TYP-C,C",
                "TYP-D,D",
                "U34,3/4 ATAU 4/4 HOOK",
                "UG,Urn Garden",
                "UN,Urn",
                "V34,3/4 ATAU 4/4 HOOK",
                "VAL,VALENCIA",
                "VAT,VALENTIA",
                "VDC,VILLA de CORDOBA",
                "VDG,VILLA de GRANADA",
                "VDM,VILLA de MALLORCA",
                "VDR,VILLA DEL REY",
                "VE0,VERNACULAR (1LT)",
                "VE1,VERNACULAR Sdt.(1LT)",
                "VEG,Vega (3.5 Lt)",
                "VEN,VENICE",
                "VER,VERSAILLES (2LT)",
                "VES,VERSAILLES (2LT)",
                "VEX,VERSAILLES (2LT)",
                "VIC,VICTORIA",
                "VIE,VIENNA",
                "VIL,VILLAGIO",
                "VISTA,Vista",
                "VLA,VILLA",
                "VOL,VOLENDAM",
                "VR0,VERANDAH (2LT)",
                "VR2,VERANDAH (2LT/Ops.1)",
                "VRN,VERONA",
                "VSG,VILLA SAN GIORGIO",
                "W-1A,1BR Deluxe",
                "W-1B,1BR Premium",
                "W-1D,W-1D",
                "W-1E,W-1E",
                "W-1F,W-1F",
                "W-1G,W-1G",
                "W-1H,W-1H",
                "W-1J,1BR Suite Corner",
                "W-2B,W-2B",
                "W-2C,W-2C",
                "W-2D,2BR Deluxe",
                "W-2E,2BR Deluxe",
                "W-2F,2BR Deluxe Corner",
                "W-2H,2BR Suite Corner",
                "W-2I,W-2I",
                "W-2K,2BR Deluxe Corner",
                "W-2L,2BR Deluxe Corner",
                "W-3A,W-3A",
                "W-3I,3BR Suite Corner",
                "WAL,WallStreet",
                "WAN,WANTILAN",
                "WAR,WARIGE",
                "WBR,WOODBRIDGE",
                "WBY,WESTIN BAY",
                "WD0,WOODLAWN",
                "WD1,WOODLAWN Sdt.",
                "WDI,WHITE DIAMOND",
                "WEL,WELLINGTON",
                "WES,WESTBURY",
                "WIL,WILSHIRE",
                "WIN,WINDSOR",
                "Wlw,Willow",
                "WMI,WESTMINSTER",
                "WMR,WINDEMERE",
                "WSA,WHITE SAPPHIRE",
                "WSC,WHITE  SAPPHIRE COR.",
                "WSDG,Wallstreet Design",
                "WWO,WESTWOOD",
                "XXX,NOT DEFINED",
                "YKO,YOKO",
                "YUCA,Yucca",
                "ZGZ,ZARAGOZA (2LT)",
                "ZUR,Zurich",
                "ZZZ,SALES OFFICE",
            };
            foreach (var item in listDetail)
            {
                var detailSeparate = item.Split(',');

                var detailPush = new MS_Detail()
                {
                    entityID = 1,
                    detailCode = detailSeparate[0],
                    detailName = detailSeparate[1],
                    isMultiple = null

                };

                InitialDetail.Add(detailPush);
            }

            foreach (var detail in InitialDetail)
            {
                AddIfNotExists(detail);
            }
        }

        private void AddIfNotExists(MS_Detail detail)
        {
            if (_context.MS_Detail.Any(l => l.detailCode == detail.detailCode))
            {
                return;
            }

            _context.MS_Detail.Add(detail);

            _context.SaveChanges();
        }
    }
}
