// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using VDI.Demo.EntityFrameworkCore;

namespace VDI.Demo.Migrations.AccountingDb
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20180222053809_initial_create_accountingDb")]
    partial class initial_create_accountingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VDI.Demo.AccountingDB.MS_JournalType", b =>
                {
                    b.Property<string>("entityCode")
                        .HasMaxLength(1);

                    b.Property<string>("journalTypeCode")
                        .HasMaxLength(11);

                    b.Property<string>("COACodeFIN")
                        .HasMaxLength(5);

                    b.Property<short>("ACCAlloc");

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("amtTypeCode")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.HasKey("entityCode", "journalTypeCode", "COACodeFIN");

                    b.HasAlternateKey("COACodeFIN", "entityCode", "journalTypeCode");

                    b.ToTable("MS_JournalType");
                });

            modelBuilder.Entity("VDI.Demo.AccountingDB.MS_Mapping", b =>
                {
                    b.Property<string>("entityCode")
                        .HasMaxLength(1);

                    b.Property<string>("journalTypeCode")
                        .HasMaxLength(11);

                    b.Property<string>("othersTypeCode")
                        .HasMaxLength(3);

                    b.Property<string>("payForCode")
                        .HasMaxLength(3);

                    b.Property<string>("payTypeCode")
                        .HasMaxLength(3);

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.HasKey("entityCode", "journalTypeCode", "othersTypeCode", "payForCode", "payTypeCode");

                    b.ToTable("MS_Mapping");
                });

            modelBuilder.Entity("VDI.Demo.AccountingDB.TR_Journal", b =>
                {
                    b.Property<string>("entityCode")
                        .HasMaxLength(1);

                    b.Property<string>("journalCode")
                        .HasMaxLength(30);

                    b.Property<string>("COACodeFIN")
                        .HasMaxLength(5);

                    b.Property<string>("COACodeAcc")
                        .HasMaxLength(5);

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<decimal>("debit")
                        .HasColumnType("money");

                    b.Property<DateTime>("journalDate");

                    b.Property<decimal>("kredit")
                        .HasColumnType("money");

                    b.Property<string>("remarks")
                        .HasMaxLength(50);

                    b.HasKey("entityCode", "journalCode", "COACodeFIN", "COACodeAcc");

                    b.HasAlternateKey("COACodeAcc", "COACodeFIN", "entityCode", "journalCode");

                    b.ToTable("TR_Journal");
                });

            modelBuilder.Entity("VDI.Demo.AccountingDB.TR_PaymentDetailJournal", b =>
                {
                    b.Property<string>("entityCode")
                        .HasMaxLength(1);

                    b.Property<string>("accCode")
                        .HasMaxLength(5);

                    b.Property<string>("transNo")
                        .HasMaxLength(20);

                    b.Property<int>("payNo");

                    b.Property<string>("bookCode")
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("journalCode")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("entityCode", "accCode", "transNo", "payNo", "bookCode");

                    b.HasAlternateKey("accCode", "bookCode", "entityCode", "payNo", "transNo");

                    b.ToTable("TR_PaymentDetailJournal");
                });
#pragma warning restore 612, 618
        }
    }
}
